### ISSUE TITLE
One step deployment

### ISSUE THREAD

**Issue by FakeYou** [FakeYou/nolli#1]
The project should have a one step deployment of the entire monorepo meaning all the packages. Deployment will be done to now.sh for now.

- [x] Setup now.sh deployment for `web` #2 
- [x] Setup now.sh deployment for `api` #3 
- [x] Setup environment so packages can communicate #4
- [x] Setup now.sh alias/subdomain per branch #5
